In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# one-hot encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [10]:
asdf = pd.read_csv("./data/asdf.csv")
asdf

,마명,승률(%),복승률(%),경주번호,경주명,거리,군(등급),번호,순위,출전두수,주로상태,기록,S1F기록,G3F기록,G1F기록,수득상금,부담중량,마체중,기수,조교사
0,가나패션,0.0,66.6,22-11-13-9,일반,1200,혼4등급,2,3,8,포화,72.6,13.7,36.3,12.4,8400000,51.0,461,김용근,안해양
1,가나패션,0.0,66.6,22-10-09-5,일반,1200,국5등급,7,2,8,다습,74.0,13.6,37.3,12.8,8800000,54.5,463,문세영,안해양
2,가나패션,0.0,66.6,22-08-13-7,일반,1200,국5등급,1,2,12,포화,73.7,13.3,37.5,12.8,8800000,52.5,468,장추열,안해양
3,가나패션,0.0,66.6,22-07-10-4,일반,1300,국5등급,7,3,7,다습,82.1,13.8,39.0,12.8,5600000,52.0,462,다비드,안해양
4,가나패션,0.0,66.6,22-06-11-2,일반,1200,국6등급,7,2,12,건조,75.3,13.7,38.3,12.9,8800000,54.0,459,다비드,안해양
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10384,히트에이스,0.0,16.6,21-06-05-2,일반,1200,국6등급,11,5,13,포화,76.7,13.7,39.3,13.5,1540000,54.0,473,함완식,이관호
10385,히트에이스,0.0,16.6,21-04-24-3,일반,1300,국6등급,2,7,14,건조,83.4,13.5,40.3,14.2,0,55.0,479,함완식,이관호
10386,히트에이스,0.0,16.6,21-01-15-2,일반,1200,국6등급,2,6,12,양호,78.1,13.9,40.8,14.6,0,54.5,471,박현우,이관호
10387,히트파워,50.0,50.0,22-10-02-8,문화일보배(L),1200,국OPEN,11,12,14,양호,75.8,13.5,40.2,14.7,0,55.0,476,최범현,우창구
10388,히트파워,50.0,50.0,22-08-21-2,일반,1000,국6등급,1,1,12,포화,61.7,13.2,37.6,13.3,33000000,55.0,476,최범현,우창구

In [11]:
asdf.drop(columns=['승률(%)', '복승률(%)'], inplace=True)
asdf

,마명,경주번호,경주명,거리,군(등급),번호,순위,출전두수,주로상태,기록,S1F기록,G3F기록,G1F기록,수득상금,부담중량,마체중,기수,조교사
0,가나패션,22-11-13-9,일반,1200,혼4등급,2,3,8,포화,72.6,13.7,36.3,12.4,8400000,51.0,461,김용근,안해양
1,가나패션,22-10-09-5,일반,1200,국5등급,7,2,8,다습,74.0,13.6,37.3,12.8,8800000,54.5,463,문세영,안해양
2,가나패션,22-08-13-7,일반,1200,국5등급,1,2,12,포화,73.7,13.3,37.5,12.8,8800000,52.5,468,장추열,안해양
3,가나패션,22-07-10-4,일반,1300,국5등급,7,3,7,다습,82.1,13.8,39.0,12.8,5600000,52.0,462,다비드,안해양
4,가나패션,22-06-11-2,일반,1200,국6등급,7,2,12,건조,75.3,13.7,38.3,12.9,8800000,54.0,459,다비드,안해양
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10384,히트에이스,21-06-05-2,일반,1200,국6등급,11,5,13,포화,76.7,13.7,39.3,13.5,1540000,54.0,473,함완식,이관호
10385,히트에이스,21-04-24-3,일반,1300,국6등급,2,7,14,건조,83.4,13.5,40.3,14.2,0,55.0,479,함완식,이관호
10386,히트에이스,21-01-15-2,일반,1200,국6등급,2,6,12,양호,78.1,13.9,40.8,14.6,0,54.5,471,박현우,이관호
10387,히트파워,22-10-02-8,문화일보배(L),1200,국OPEN,11,12,14,양호,75.8,13.5,40.2,14.7,0,55.0,476,최범현,우창구
10388,히트파워,22-08-21-2,일반,1000,국6등급,1,1,12,포화,61.7,13.2,37.6,13.3,33000000,55.0,476,최범현,우창구

In [14]:
asdf_sort = asdf.sort_values(by=["경주번호","기록"], ascending=[False,True])
asdf = asdf_sort
asdf

,마명,경주번호,경주명,거리,군(등급),번호,순위,출전두수,주로상태,기록,S1F기록,G3F기록,G1F기록,수득상금,부담중량,마체중,기수,조교사
2701,리월마,22-11-13-9,일반,1200,혼4등급,3,2,8,포화,71.6,13.3,35.6,12.4,13200000,54.0,469,문세영,서홍수
3398,문학스톰,22-11-13-9,일반,1200,혼4등급,1,1,8,포화,71.6,13.3,35.8,12.4,33000000,53.0,525,장추열,정호익
0,가나패션,22-11-13-9,일반,1200,혼4등급,2,3,8,포화,72.6,13.7,36.3,12.4,8400000,51.0,461,김용근,안해양
5829,알렉산더원,22-11-13-9,일반,1200,혼4등급,7,4,8,포화,72.6,14.5,35.8,12.4,3000000,55.5,491,송재철,우창구
327,국제공항,22-11-13-9,일반,1200,혼4등급,4,5,8,포화,73.5,13.9,36.9,13.1,2400000,52.0,472,먼로,강환민
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7611,제이에스군주,19-09-21-7,일반,1000,혼4등급,5,4,12,건조,61.5,14.6,36.0,12.6,3750000,55.0,494,김동수,박재우
4939,소울메리트,19-09-21-7,일반,1000,혼4등급,3,7,12,건조,62.4,14.1,37.7,13.4,0,55.0,512,송재철,안병기
258,골든서비스,19-09-21-7,일반,1000,혼4등급,10,8,12,건조,62.8,13.8,38.2,13.7,0,55.0,496,안토니오,최용구
6317,옥룡,19-09-21-7,일반,1000,혼4등급,11,9,12,건조,62.9,13.9,38.2,13.8,0,55.0,486,다나카,강성오
7473,정문에이스,19-09-21-7,일반,1000,혼4등급,7,12,12,건조,63.5,14.9,37.5,13.3,0,55.0,491,김태훈,홍대유

In [15]:
asdf = asdf[::-1]
asdf = asdf.reset_index()
asdf.drop(columns='index', inplace=True)
asdf

,마명,경주번호,경주명,거리,군(등급),번호,순위,출전두수,주로상태,기록,S1F기록,G3F기록,G1F기록,수득상금,부담중량,마체중,기수,조교사
0,정문에이스,19-09-21-7,일반,1000,혼4등급,7,12,12,건조,63.5,14.9,37.5,13.3,0,55.0,491,김태훈,홍대유
1,옥룡,19-09-21-7,일반,1000,혼4등급,11,9,12,건조,62.9,13.9,38.2,13.8,0,55.0,486,다나카,강성오
2,골든서비스,19-09-21-7,일반,1000,혼4등급,10,8,12,건조,62.8,13.8,38.2,13.7,0,55.0,496,안토니오,최용구
3,소울메리트,19-09-21-7,일반,1000,혼4등급,3,7,12,건조,62.4,14.1,37.7,13.4,0,55.0,512,송재철,안병기
4,제이에스군주,19-09-21-7,일반,1000,혼4등급,5,4,12,건조,61.5,14.6,36.0,12.6,3750000,55.0,494,김동수,박재우
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10384,국제공항,22-11-13-9,일반,1200,혼4등급,4,5,8,포화,73.5,13.9,36.9,13.1,2400000,52.0,472,먼로,강환민
10385,알렉산더원,22-11-13-9,일반,1200,혼4등급,7,4,8,포화,72.6,14.5,35.8,12.4,3000000,55.5,491,송재철,우창구
10386,가나패션,22-11-13-9,일반,1200,혼4등급,2,3,8,포화,72.6,13.7,36.3,12.4,8400000,51.0,461,김용근,안해양
10387,문학스톰,22-11-13-9,일반,1200,혼4등급,1,1,8,포화,71.6,13.3,35.8,12.4,33000000,53.0,525,장추열,정호익
10388,리월마,22-11-13-9,일반,1200,혼4등급,3,2,8,포화,71.6,13.3,35.6,12.4,13200000,54.0,469,문세영,서홍수

In [17]:
asdf["순위"].value_counts()

1       1125
2       1072
3       1063
4       1046
5        980
6        951
7        934
8        867
9        726
10       642
11       490
12       320
13        94
14        50
주행중지      22
실격         3
17         3
16         1
Name: 순위, dtype: int64

In [45]:
#순위의 주행중지, 실격 값을 15로 바꿉니다

asdf = asdf.replace(["주행중지", "실격"], [15, 15])
asdf["순위"].value_counts()

1     1125
2     1072
3     1063
4     1046
5      980
6      951
7      934
8      867
9      726
10     642
11     490
12     320
13      94
14      50
15      25
17       3
16       1
Name: 순위, dtype: int64